name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Run detekt
        run: ./gradlew detekt

  spotless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Run spotless check
        run: ./gradlew spotlessCheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Run tests
        run: ./gradlew test

  code-coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Run code coverage check
        run: ./gradlew jacocoTestCoverageVerification
      - name: Generate code coverage report
        run: ./gradlew jacocoTestReport
